# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censusdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census2010households',
            name='female_no_husband',
            field=models.IntegerField(help_text='Female householder, no husband present. Combine with male_no_wife to check total_family_other. P0180006'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='husband_wife',
            field=models.IntegerField(help_text='Husband-wife family households. Combine with total_family_other to check total_family. P0180003'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='living_alone',
            field=models.IntegerField(help_text='Householder living alone. Combine with not_living_alone to check total_nonfamily. P0180008'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='male_no_wife',
            field=models.IntegerField(help_text='Male householder, no wife present. Combine with female_no_husband to check total_family_other. P0180005'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='not_living_alone',
            field=models.IntegerField(help_text='Householder not living alone. Combine with living_alone to check total_nonfamily. P0180009'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='total',
            field=models.IntegerField(help_text='Total number of households in census tract. P0180001'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='total_family',
            field=models.IntegerField(help_text='Total number of family households. Combined with total_nonfamily to check total. P0180002'),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='total_family_other',
            field=models.IntegerField(help_text="'Other' family households. Combine with husband_wife to check total_family. P0180004"),
        ),
        migrations.AlterField(
            model_name='census2010households',
            name='total_nonfamily',
            field=models.IntegerField(help_text='Total number of nonfamily households. Combine with total_family to check total. P0180007'),
        ),
    ]
