language: python
python:
  - "2.6"
  - "2.7"
install:
  - sudo apt-get install python-software-properties
  - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install postgresql-9.1-postgis
  - sudo su postgres -c "createuser -s -d tester"
  - sudo su postgres -c "createdb -O tester travisdb"
  - sudo su postgres -c "echo 'CREATE EXTENSION postgis;' | psql travisdb"
  - |
    echo "DATABASES = {'default': {'ENGINE': 'django.contrib.gis.db.backends.postgis', 'NAME': 'travisdb', 'USER': 'tester'}}" > institutions/institutions/settings/local_settings.py
  - cd institutions
  - pip install -r requirements.txt
script:
  - python manage.py test
