language: python
python:
  - "3.6.4"
install:
  - pip install pipenv
  - pipenv install --dev
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE travisdb;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travisdb
env:
  - DATABASE_URL="postgis://postgres@localhost/travisdb"\
    DEBUG="true"\
    USING_SSL="False"
script:
  - pipenv run pytest --cov
after_success:
  - pipenv run coveralls
