version: '3.3'
services:
  database:
    image: mdillon/postgis:10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - data:/var/lib/postgresql/data
  app: &APP
    build: .
    volumes:
    - .:/app
    depends_on:
    - database
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-["localhost", "0.0.0.0", "127.0.0.1"]}
      DATABASE_URL: postgis://postgres@database/postgres
      DEBUG: ${DEBUG:-true}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN:-pk.eyJ1IjoiY2ZwYiIsImEiOiJodmtiSk5zIn0.VkCynzmVYcLBxbyHzlvaQw}
      PIPENV_SHELL_FANCY: "true"
      PIPENV_VENV_IN_PROJECT: "true"
      PYTHONUNBUFFERED: "1"
      USING_SSL: "False"
    command: .docker/wait_for_db_then pipenv run .docker/start_server.sh
  worker:
    <<: *APP
    command: .docker/wait_for_db_then pipenv run python manage.py process_tasks
    volumes:
    - .:/app
    - media:/app/media/
  proxy:
    image: nginx:1.13-alpine
    volumes:
    - .docker/nginx.conf.tpl:/etc/nginx/nginx.conf.tpl:ro
    - .docker/start_proxy.sh:/usr/sbin/start_proxy.sh
    - media:/etc/nginx/html/media/
    ports:
    - 8000:8000
    depends_on:
    - app
    environment:
      NGINX_HOST: ${NGINX_HOST:-localhost}
    command: start_proxy.sh

volumes:
  data:
  media:
