version: '3.3'
services:
  database:
    image: mdillon/postgis:10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - data:/var/lib/postgresql/data
  app:
    build: .
    volumes:
    - .:/app
    depends_on:
    - database
    environment:
      DATABASE_URL: postgis://postgres@database/postgres
      DJANGO_SETTINGS_MODULE: mapusaurus.settings.docker
    command: .docker/wait_for_db_then pipenv run python mapusaurus/manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
volumes:
  data:
  search_data:
