# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 04:58
from __future__ import unicode_literals
from typing import List

import django.contrib.postgres.operations
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    replaces = [('respondents', '0001_initial'), ('respondents', '0002_auto_20160222_1706'), ('respondents', '0003_auto_20171215_1812'), ('respondents', '0004_auto_20171227_2123'), ('respondents', '0005_auto_20171227_2322'), ('respondents', '0006_auto_20180212_0524'), ('respondents', '0007_auto_20180218_1817'), ('respondents', '0008_auto_20180218_1821'), ('respondents', '0009_auto_20180309_0355'), ('respondents', '0010_auto_20180311_2316'), ('respondents', '0011_institution_num_loans'), ('respondents', '0012_auto_20180313_0123'), ('respondents', '0013_auto_20181113_2323'), ('respondents', '0014_auto_20181229_0439')]

    initial = True

    dependencies: List[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('hmda_id', models.IntegerField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('lat', models.FloatField(help_text='y')),
                ('lon', models.FloatField(help_text='x')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('year', models.SmallIntegerField(db_index=True)),
                ('respondent_id', models.CharField(max_length=10)),
                ('institution_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tax_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
                ('mailing_address', models.CharField(max_length=64)),
                ('assets', models.BigIntegerField(blank=True, help_text='Prior year reported assets in thousands of dollars', null=True)),
                ('rssd_id', models.CharField(blank=True, help_text='From Reporter Panel. Id on the National Information Center repository', max_length=10, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='LenderHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='ParentInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('rssd_id', models.CharField(blank=True, help_text='Id on the National Information Center repository', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipcodeCityStateYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('plus_four', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=25)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='zipcodecitystateyear',
            unique_together=set([('zip_code', 'city', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='parentinstitution',
            unique_together=set([('rssd_id', 'year')]),
        ),
        migrations.AddField(
            model_name='institution',
            name='non_reporting_parent',
            field=models.ForeignKey(blank=True, help_text='Non-HMDA reporting parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='respondents.ParentInstitution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent institution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='respondents.Institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='top_holder',
            field=models.ForeignKey(blank=True, help_text='The company at the top of the ownership chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='respondents.ParentInstitution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.ZipcodeCityStateYear'),
        ),
        migrations.AddField(
            model_name='branch',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.Institution'),
        ),
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS btree_gin',
        ),
        migrations.AddField(
            model_name='institution',
            name='num_loans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunSQL(
            sql=' CREATE INDEX lender_search\n                ON respondents_institution\n                USING gin(year, name gin_trgm_ops)\n                WHERE num_loans > 0\n            ',
            reverse_sql='DROP INDEX lender_search',
        ),
    ]
