# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 05:24
from __future__ import unicode_literals

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0005_auto_20171227_2322'),
    ]

    operations = [
        TrigramExtension(),
    ]
