# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0007_auto_20180218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='non_reporting_parent',
            field=models.ForeignKey(blank=True, help_text='Non-HMDA reporting parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='respondents.ParentInstitution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent institution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='respondents.Institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='rssd_id',
            field=models.CharField(blank=True, help_text='From Reporter Panel. Id on the National Information Center repository', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='top_holder',
            field=models.ForeignKey(blank=True, help_text='The company at the top of the ownership chain.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='respondents.ParentInstitution'),
        ),
        migrations.AlterField(
            model_name='parentinstitution',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parentinstitution',
            name='rssd_id',
            field=models.CharField(blank=True, help_text='Id on the National Information Center repository', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parentinstitution',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='zipcodecitystateyear',
            name='plus_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='institution',
            index_together=set([]),
        ),
    ]
