# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0008_auto_20180218_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='year',
            field=models.SmallIntegerField(db_index=True),
        ),
    ]
