# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0009_auto_20180309_0355'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gin"),
        migrations.RunSQL(
            """ CREATE INDEX lender_search
                ON respondents_institution
                USING gin(year, name gin_trgm_ops)
            """,
            """ DROP INDEX lender_search """,
        ),
    ]
