# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.expressions import RawSQL


def forward(apps, schema_editor):
    Institution = apps.get_model('respondents', 'Institution')
    Institution.objects.update(num_loans=RawSQL("""
        SELECT count(*)
        FROM hmda_hmdarecord
        WHERE hmda_hmdarecord.institution_id =
            respondents_institution.institution_id
    """, tuple()))


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0009_auto_20181117_2048'),
        ('respondents', '0010_auto_20180311_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='num_loans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
