# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0011_institution_num_loans'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX lender_search",
            """ CREATE INDEX lender_search
                ON respondents_institution
                USING gin(year, name gin_trgm_ops)
            """,
        ),
        migrations.RunSQL(
            """ CREATE INDEX lender_search
                ON respondents_institution
                USING gin(year, name gin_trgm_ops)
                WHERE num_loans > 0
            """,
            "DROP INDEX lender_search",
        ),
    ]
