# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0012_auto_20180313_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='assets',
            field=models.BigIntegerField(blank=True, help_text='Prior year reported assets in thousands of dollars', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='mailing_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='parentinstitution',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
