# Generated by Django 2.1.4 on 2019-01-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20190120_0352'),
        ('ffiec', '0003_lowpopulationdemographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetDivDemographics',
            fields=[
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('median_family_income', models.PositiveIntegerField()),
                ('median_household_income', models.PositiveIntegerField()),
                ('ffiec_est_med_fam_income', models.PositiveIntegerField(help_text='FFIEC Estimated Median Family Income')),
                ('composite_key', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('metdiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='geo.MetroDivision')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
