# Generated by Django 2.1.7 on 2019-02-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW reports_incomehousingreport AS
            (SELECT
                year || county_id AS compound_id,
                year,
                county_id,
                SUM(single_family_homes) AS home_total,
                SUM(single_family_occupied) AS occupied,
                COUNT(composite_key) AS tract_total,
                COUNT(composite_key) FILTER (
                    WHERE income_indicator IN ('low', 'mod')
                ) AS lmi_tracts,
                COUNT(composite_key) FILTER (
                    WHERE non_hispanic_white < persons / 2
                ) AS min_tracts,
                SUM(persons) AS pop_total,
                SUM(persons) FILTER (
                    WHERE income_indicator IN ('low', 'mod')
                ) AS pop_lmi,
                SUM(persons) FILTER (
                    WHERE non_hispanic_white < persons / 2
                ) AS pop_min
                FROM ffiec_tractdemographics
                INNER JOIN geo_tract ON (tract_id = geoid)
                GROUP BY year, county_id
            )
            """,
            "DROP MATERIALIZED VIEW reports_incomehousingreport",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX reports_incomehousingreport_idx
            ON reports_incomehousingreport (year, county_id)
            """,
            "DROP INDEX reports_incomehousingreport_idx",
        ),
    ]
