# Generated by Django 2.1.7 on 2019-02-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_incomehousingreport'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW reports_disparityreport AS
            (SELECT
                as_of_year 
                || tract.county_id
                || CASE WHEN action_taken = 1 THEN 'A' ELSE 'D' END
                || lien_status
                || loan_purpose
                || owner_occupancy
                || property_type
                AS compound_id,
                as_of_year AS year,
                tract.county_id,
                action_taken = 1 AS approved,
                lien_status,
                loan_purpose,
                owner_occupancy,
                property_type,
                COUNT(hmda_record_id) AS all_records,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_ethnicity = '2'
                    AND applicant_race_1 = '5'
                ) AS white,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_ethnicity = '2'
                    AND applicant_race_1 = '3'
                ) AS black,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_ethnicity = '1'
                ) AS hispanic,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_ethnicity = '2'
                    AND applicant_race_1 = '2'
                ) AS asian,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_ethnicity = '1'
                    OR applicant_race_1 IN ('1', '2', '3', '4')
                ) AS minb,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_income_000s < (
                        COALESCE(
                            metdivdem.ffiec_est_med_fam_income,
                            cbsadem.ffiec_est_med_fam_income,
                            lowpopdem.ffiec_est_med_fam_income,
                            0
                        ) * .8 / 1000
                    )
                ) AS lmib,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_income_000s >= (
                        COALESCE(
                            metdivdem.ffiec_est_med_fam_income,
                            cbsadem.ffiec_est_med_fam_income,
                            lowpopdem.ffiec_est_med_fam_income,
                            0
                        ) * .8 / 1000
                    )
                ) AS muib,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_sex = 2
                ) AS female,
                COUNT(hmda_record_id) FILTER (
                    WHERE applicant_sex = 1
                ) AS male,
                COUNT(hmda_record_id) FILTER (
                    WHERE tractdem.income_indicator IN ('low', 'mod')
                ) AS lmit,
                COUNT(hmda_record_id) FILTER (
                    WHERE tractdem.income_indicator IN ('mid', 'high')
                ) AS muit,
                COUNT(hmda_record_id) FILTER (
                    WHERE tractdem.non_hispanic_white
                    < tractdem.persons / 2
                ) AS mint,
                COUNT(hmda_record_id) FILTER (
                    WHERE tractdem.non_hispanic_white
                    >= tractdem.persons / 2
                ) AS whitet
                FROM hmda_loanapplicationrecord lar
                INNER JOIN geo_tract tract ON (lar.tract_id = tract.geoid)
                INNER JOIN geo_county county
                    ON (tract.county_id = county.geoid)
                LEFT JOIN ffiec_tractdemographics tractdem
                    ON (tractdem.tract_id = lar.tract_id
                        AND tractdem.year = as_of_year)
                LEFT JOIN ffiec_metdivdemographics metdivdem
                    ON (metdivdem.metdiv_id = county.metdiv_id
                        AND metdivdem.year = as_of_year)
                LEFT JOIN ffiec_cbsademographics cbsadem
                    ON (cbsadem.cbsa_id = county.cbsa_id
                        AND cbsadem.year = as_of_year)
                LEFT JOIN ffiec_lowpopulationdemographics lowpopdem
                    ON (lowpopdem.state_id = county.state_id
                        AND lowpopdem.year = as_of_year)
                WHERE action_taken <= 5
                GROUP BY (
                    as_of_year,
                    tract.county_id,
                    action_taken = 1,
                    lien_status,
                    loan_purpose,
                    owner_occupancy,
                    property_type
                )
            )
            """,
            "DROP MATERIALIZED VIEW reports_disparityreport",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX reports_disparityreport_idx
            ON reports_disparityreport (
                year, county_id, approved,
                lien_status, loan_purpose, owner_occupancy, property_type
            )
            """,
            "DROP INDEX reports_disparityreport_idx",
        ),
    ]
