# Generated by Django 2.1.7 on 2019-02-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_disparityreport'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW reports_lenderreport AS
            (SELECT
                as_of_year 
                || tract.county_id
                || lien_status
                || loan_purpose
                || owner_occupancy
                || property_type
                || lender.institution_id
                AS compound_id,
                as_of_year AS year,
                tract.county_id,
                lien_status,
                loan_purpose,
                owner_occupancy,
                property_type,
                lender.institution_id AS lender_id,
                lender.name AS lender_name,
                COUNT(hmda_record_id) AS applications,
                COUNT(hmda_record_id) FILTER (
                    WHERE action_taken = 1
                ) AS approved,
                COUNT(hmda_record_id) FILTER (
                    WHERE action_taken = 1
                    AND tractdem.income_indicator IN ('low', 'mod')
                ) AS lmit_approved,
                COUNT(hmda_record_id) FILTER (
                    WHERE action_taken = 1
                    AND applicant_income_000s < (
                        COALESCE(
                            metdivdem.ffiec_est_med_fam_income,
                            cbsadem.ffiec_est_med_fam_income,
                            lowpopdem.ffiec_est_med_fam_income,
                            0
                        ) * .8 / 1000
                    )
                ) AS lmib_approved,
                COUNT(hmda_record_id) FILTER (
                    WHERE action_taken = 1
                    AND tractdem.non_hispanic_white < tractdem.persons / 2
                ) AS mint_approved,
                COUNT(hmda_record_id) FILTER (
                    WHERE action_taken = 1
                    AND (
                        applicant_ethnicity = '1'
                        OR applicant_race_1 IN ('1', '2', '3', '4')
                    )
                ) AS minb_approved
                FROM hmda_loanapplicationrecord lar
                INNER JOIN geo_tract tract ON (lar.tract_id = tract.geoid)
                INNER JOIN geo_county county
                    ON (tract.county_id = county.geoid)
                INNER JOIN respondents_institution lender ON (
                    lar.institution_id = lender.institution_id
                )
                LEFT JOIN ffiec_tractdemographics tractdem
                    ON (tractdem.tract_id = lar.tract_id
                        AND tractdem.year = as_of_year)
                LEFT JOIN ffiec_metdivdemographics metdivdem
                    ON (metdivdem.metdiv_id = county.metdiv_id
                        AND metdivdem.year = as_of_year)
                LEFT JOIN ffiec_cbsademographics cbsadem
                    ON (cbsadem.cbsa_id = county.cbsa_id
                        AND cbsadem.year = as_of_year)
                LEFT JOIN ffiec_lowpopulationdemographics lowpopdem
                    ON (lowpopdem.state_id = county.state_id
                        AND lowpopdem.year = as_of_year)
                WHERE action_taken <= 5
                GROUP BY (
                    as_of_year,
                    tract.county_id,
                    lien_status,
                    loan_purpose,
                    owner_occupancy,
                    property_type,
                    lender.institution_id,
                    lender.name
                )
            )
            """,
            "DROP MATERIALIZED VIEW reports_lenderreport",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX reports_lenderreport_idx
            ON reports_lenderreport (
                year, county_id,
                lien_status, loan_purpose, owner_occupancy, property_type
            )
            """,
            "DROP INDEX reports_lenderreport_idx",
        ),
    ]
