# Generated by Django 2.1.4 on 2019-01-21 02:11

from django.db import migrations, models


def forward(apps, schema_editor):
    LoanApplicationRecord = apps.get_model('hmda', 'LoanApplicationRecord')
    LoanApplicationRecord.objects\
        .filter(applicant_income_000s="NA")\
        .update(applicant_income_000s=None)


def backward(apps, schema_editor):
    LoanApplicationRecord = apps.get_model('hmda', 'LoanApplicationRecord')
    LoanApplicationRecord.objects\
        .filter(applicant_income_000s=None)\
        .update(applicant_income_000s="NA")


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0001_squashed_0012_laryear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationrecord',
            name='applicant_income_000s',
            field=models.CharField(blank=True, help_text='The gross annual income that the lender relied on when evaluating the creditworthiness of the applicant, rounded to the nearest thousand.', max_length=8, null=True),
        ),
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='loanapplicationrecord',
            name='applicant_income_000s',
            field=models.PositiveIntegerField(blank=True, help_text='The gross annual income that the lender relied on when evaluating the creditworthiness of the applicant, rounded to the nearest thousand.', null=True),
        ),
    ]
