# Generated by Django 2.1.7 on 2019-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0002_auto_20190121_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laryear',
            options={'managed': False, 'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='loanapplicationrecord',
            name='application_date_indicator',
            field=models.PositiveIntegerField(choices=[(0, 'Application Date >= 01-01-2004'), (1, 'Application Date < 01-01-2004'), (2, 'Application Date = NA (Not Available)')], help_text='A code representing the date of the application. "0" means the application was made on or after 1/1/2004; "1" means the application was made before 1/1/2004; "2" means the application date is not available.'),
        ),
        migrations.AlterField(
            model_name='loanapplicationrecord',
            name='owner_occupancy',
            field=models.PositiveIntegerField(choices=[(1, 'Owner-occupied as a principal dwelling'), (2, 'Not owner-occupied'), (3, 'Not applicable')], help_text='A code representing the owner-occupancy status of the property. Second homes, vacation homes, and rental properties are classified as "not owner-occupied as a principal dwelling".'),
        ),
        migrations.RunSQL(
            "DROP TABLE hmda_laryear",
            "CREATE TABLE hmda_laryear (year INTEGER PRIMARY KEY)",
        ),
        migrations.RunSQL(
            """
                CREATE MATERIALIZED VIEW hmda_laryear
                AS (
                    SELECT as_of_year AS year
                    FROM hmda_loanapplicationrecord
                    GROUP BY as_of_year
                )
            """,
            "DROP MATERIALIZED VIEW hmda_laryear",
        ),
    ]
