# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0003_auto_20180212_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdarecord',
            name='action_taken',
            field=models.PositiveIntegerField(choices=[(1, 'Loan originated'), (2, 'Application approved but not accepted'), (3, 'Application denied by financial institution'), (4, 'Application withdrawn by applicant'), (5, 'File closed for incompleteness'), (6, 'Loan purchased by the institution'), (7, 'Preapproval request denied by financial institution'), (8, 'Preapproval request approved but not accepted (optional reporting)')], db_index=True, help_text='A code representing the action taken on the loan or application, such as whether an application was approved or denied. Loan originated means the application resulted in a mortgage. Loan purchased means that the lender bought the loan on the secondary market.'),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='agency_code',
            field=models.CharField(choices=[(1, 'Office of the Comptroller of the Currency (OCC)'), (2, 'Federal Reserve System (FRS)'), (3, 'Federal Deposit Insurance Corporation (FDIC)'), (5, 'National Credit Union Administration (NCUA)'), (7, 'Department of Housing and Urban Development (HUD)'), (9, 'Consumer Financial Protection Bureau (CFPB)')], help_text='A code representing the federal agency to which the HMDA-reporting institution submits its HMDA data.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_ethnicity',
            field=models.CharField(choices=[(1, 'Hispanic or Latino'), (2, 'Not Hispanic or Latino'), (3, 'Information not provided by applicant in mail, Internet, or telephone application'), (4, 'Not applicable'), (5, 'No co-applicant')], help_text='A code representing the ethnicity of the primary applicant.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_income_000s',
            field=models.CharField(help_text='The gross annual income that the lender relied on when evaluating the creditworthiness of the applicant, rounded to the nearest thousand.', max_length=4),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_1',
            field=models.CharField(choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the first listed race for the primary applicant. The applicant can list up to five races.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_2',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the second listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_3',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the third listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_4',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fourth listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_5',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fifth listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_sex',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Information not provided by applicant in mail, Internet, or telephone application'), (4, 'Not applicable'), (5, 'No co-applicant')], help_text='A code representing the sex of the primary applicant.'),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='application_date_indicator',
            field=models.PositiveIntegerField(choices=[(0, 'Application Date >= 01-01-2004'), (1, 'Application Date < 01-01-2004'), (2, 'Application Date = NA (Not Available)')], help_text="A code representing the date of the application. '0' means the application was made on or after 1/1/2004; '1' means the application was made before 1/1/2004; '2' means the application date is not available."),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='as_of_year',
            field=models.PositiveIntegerField(db_index=True, help_text='The reporting year of the HMDA record.'),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='census_tract_number',
            field=models.CharField(help_text='The number of the census tract for the property. This code is only unique when combined with the state and county codes.', max_length=7),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_ethnicity',
            field=models.CharField(choices=[(1, 'Hispanic or Latino'), (2, 'Not Hispanic or Latino'), (3, 'Information not provided by applicant in mail, Internet, or telephone application'), (4, 'Not applicable'), (5, 'No co-applicant')], help_text='A code representing the ethnicity of the co-applicant.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_1',
            field=models.CharField(choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the first listed race for the co-applicant. The co-applicant can list up to five races.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_2',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the second listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_3',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the third listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_4',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fourth listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_5',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native  2 -- Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fifth listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_sex',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Information not provided by applicant in mail, Internet, or telephone application'), (4, 'Not applicable'), (5, 'No co-applicant')], help_text='A code representing the sex of the co-applicant.'),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='countyfp',
            field=models.CharField(help_text='A three-digit code representing the county of the property. This code is only unique when combined with the state code.', max_length=3),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='denial_reason_1',
            field=models.CharField(blank=True, choices=[(1, 'Debt-to-income ratio'), (2, 'Employment history'), (3, 'Credit history'), (4, 'Collateral'), (5, 'Insufficient cash (downpayment, closing costs)'), (6, 'Unverifiable information'), (7, 'Credit application incomplete'), (8, 'Mortgage insurance denied'), (9, 'Other')], help_text='A code representing the first reason for denial of the application. Lenders may report up to three denial reasons, but such reporting is optional.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='denial_reason_2',
            field=models.CharField(blank=True, choices=[(1, 'Debt-to-income ratio'), (2, 'Employment history'), (3, 'Credit history'), (4, 'Collateral'), (5, 'Insufficient cash (downpayment, closing costs)'), (6, 'Unverifiable information'), (7, 'Credit application incomplete'), (8, 'Mortgage insurance denied'), (9, 'Other')], help_text='A code representing the second reason for denial of the application.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='denial_reason_3',
            field=models.CharField(blank=True, choices=[(1, 'Debt-to-income ratio'), (2, 'Employment history'), (3, 'Credit history'), (4, 'Collateral'), (5, 'Insufficient cash (downpayment, closing costs)'), (6, 'Unverifiable information'), (7, 'Credit application incomplete'), (8, 'Mortgage insurance denied'), (9, 'Other')], help_text='A code representing the third reason for denial of the application.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='edit_status',
            field=models.CharField(blank=True, choices=[('', 'No edit failures'), (5, 'Validity edit failure only'), (6, 'Quality edit failure only'), (7, 'Validity and quality edit failures')], help_text='A code representing the edit failure status of the application.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='ffieic_median_family_income',
            field=models.CharField(help_text='The median family income in dollars for the MSA/MD in which the tract is located. (Note: The HMDA API names this col hud_median_family_income.)', max_length=8),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='hoepa_status',
            field=models.CharField(choices=[(1, 'HOEPA loan'), (2, 'Not a HOEPA loan')], help_text='A code representing whether a loan is subject to the Home Ownership and Equity Protection Act of 1994 (HOEPA).', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='lien_status',
            field=models.CharField(choices=[(1, 'Secured by a first lien'), (2, 'Secured by a subordinate lien'), (3, 'Not secured by a lien'), (4, 'Not applicable (purchased loans)')], help_text='A code representing the lien status. Most mortgages are secured by a lien against the property. In the event of a forced liquidation, first lien holders will generally get paid before subordinate lien holders.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='loan_amount_000s',
            field=models.PositiveIntegerField(help_text='The amount of the loan applied for, in thousands of dollars.'),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='loan_purpose',
            field=models.PositiveIntegerField(choices=[(1, 'Home purchase'), (2, 'Home improvement'), (3, 'Refinancing')], help_text='A code representing the purpose of the loan (home purchase, refinance, or home improvement).'),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='loan_type',
            field=models.PositiveIntegerField(choices=[(1, 'Conventional (any loan other than FHA, VA, FSA, or RHS loans)'), (2, 'FHA-insured (Federal Housing Administration)'), (3, 'VA-guaranteed (Veterans Administration)'), (4, 'FSA/RHS (Farm Service Agency or Rural Housing Service)')], help_text="A code representing the type of loan applied for. Many loans are insured or guaranteed by government programs offered by Federal Housing Administration (FHA), the Department of Veterans Affairs (VA), or the Department of Agriculture's Rural Housing Service (RHS) or Farm Service Agency (FSA). All other loans are classified as conventional."),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='minority_population',
            field=models.CharField(help_text='The percentage of minority population to total population for the census tract, carried to two decimal places.', max_length=6),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='msamd',
            field=models.CharField(help_text='A code representing the Metropolitan Statistical Area/Metropolitian Division (MSA/MD) the property is located in. An MSA is a region with relatively high population density at its core (usually a single large city) and close economic ties throughout. Larger MSAs are divided into MDs.', max_length=5),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='number_of_1_to_4_family_units',
            field=models.CharField(help_text='The number of dwellings in the tract that are built to house fewer than 5 families.', max_length=8),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='number_of_owner_occupied_units',
            field=models.CharField(help_text='The number of dwellings in the tract that are lived in by the owner.', max_length=8),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='owner_occupancy',
            field=models.PositiveIntegerField(choices=[(1, 'Owner-occupied as a principal dwelling'), (2, 'Not owner-occupied'), (3, 'Not applicable')], help_text="A code representing the owner-occupancy status of the property. Second homes, vacation homes, and rental properties are classified as 'not owner-occupied as a principal dwelling'."),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='population',
            field=models.CharField(help_text='The total population in the tract.', max_length=8),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='preapproval',
            field=models.CharField(choices=[(1, 'Preapproval was requested'), (2, 'Preapproval was not requested'), (3, 'Not applicable')], help_text='A code representing the pre-approval status of the application.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='property_type',
            field=models.CharField(choices=[(1, 'One to four-family (other than manufactured housing)'), (2, 'Manufactured housing'), (3, 'Multifamily')], help_text='A code representing the type of the property.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='purchaser_type',
            field=models.CharField(choices=[(0, 'Loan was not originated or was not sold in calendar year covered by register'), (1, 'Fannie Mae (FNMA)'), (2, 'Ginnie Mae (GNMA)'), (3, 'Freddie Mac (FHLMC)'), (4, 'Farmer Mac (FAMC)'), (5, 'Private securitization'), (6, 'Commercial bank, savings bank or savings association'), (7, 'Life insurance company, credit union, mortgage bank, or finance company'), (8, 'Affiliate institution'), (9, 'Other type of purchaser')], help_text='A code representing the type of institution purchasing the loan.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='rate_spread',
            field=models.CharField(help_text="The rate spread for the loan, which is the difference between the loan's annual percentage rate (APR) and the average prime offer rate (APOR).", max_length=5),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='respondent_id',
            field=models.CharField(help_text='A code representing the bank or other financial institution that is reporting the loan or application.', max_length=10),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='sequence_number',
            field=models.CharField(help_text='A one-up number scheme for each respondent to make each loan unique.', max_length=7),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='statefp',
            field=models.CharField(db_index=True, help_text='A two-digit code representing the state the property is located in.', max_length=2),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='tract_to_msamd_income',
            field=models.CharField(help_text='The percentage of the median family income for the tract compared to the median family income for the MSA/MD, rounded to two decimal places.', max_length=6),
        ),
        migrations.AlterField(
            model_name='lendingstats',
            name='fha_bucket',
            field=models.PositiveIntegerField(help_text='Predetermined buckets calculated by find fha % of total lar count'),
        ),
        migrations.AlterField(
            model_name='lendingstats',
            name='fha_count',
            field=models.PositiveIntegerField(help_text='Total HMDA LAR count where loan_type=2(FHA)'),
        ),
        migrations.AlterField(
            model_name='lendingstats',
            name='lar_count',
            field=models.PositiveIntegerField(help_text='Total HMDA LAR count'),
        ),
        migrations.AlterField(
            model_name='lendingstats',
            name='lar_median',
            field=models.PositiveIntegerField(help_text='HMDA LAR median'),
        ),
        migrations.AlterField(
            model_name='year',
            name='census_year',
            field=models.PositiveIntegerField(help_text='Year of census data.'),
        ),
        migrations.AlterField(
            model_name='year',
            name='geo_year',
            field=models.PositiveIntegerField(help_text='Year that geographic boundaries were recorded.'),
        ),
        migrations.AlterField(
            model_name='year',
            name='hmda_year',
            field=models.PositiveIntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)], help_text='The reporting year of the HMDA record.', primary_key=True, serialize=False),
        ),
    ]
