# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0004_auto_20180218_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmdarecord',
            name='hmda_record_id',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
