# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 03:27
from __future__ import unicode_literals

from django.db import migrations
from django.db.models.functions import Concat


def forward(apps, schema_editor):
    HMDARecord = apps.get_model('hmda', 'HMDARecord')
    HMDARecord.objects.update(
        hmda_record_id=Concat('institution_id', 'sequence_number')
    )


def backward(apps, schema_editor):
    HMDARecord = apps.get_model('hmda', 'HMDARecord')
    HMDARecord.objects.update(hmda_record_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0005_hmdarecord_hmda_record_id'),
    ]

    operations = [migrations.RunPython(forward, backward)]
