# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0006_auto_20180225_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmdarecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='hmda_record_id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False),
        ),
    ]
