# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0007_auto_20180225_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_1',
            field=models.CharField(choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the first listed race for the primary applicant. The applicant can list up to five races.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_2',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the second listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_3',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the third listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_4',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fourth listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_5',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fifth listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_1',
            field=models.CharField(choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the first listed race for the co-applicant. The co-applicant can list up to five races.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_2',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the second listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_3',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the third listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_4',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fourth listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_5',
            field=models.CharField(blank=True, choices=[(1, 'American Indian or Alaska Native'), (2, 'Asian'), (3, 'Black or African American'), (4, 'Native Hawaiian or Other Pacific Islander '), (5, 'White'), (6, 'Information not provided by applicant in mail, Internet, or telephone application'), (7, 'Not applicable'), (8, 'No co-applicant')], help_text='A code representing the fifth listed race for the co-applicant.', max_length=1, null=True),
        ),
    ]
