# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0008_auto_20180331_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdarecord',
            name='agency_code',
            field=models.CharField(choices=[('1', 'Office of the Comptroller of the Currency (OCC)'), ('2', 'Federal Reserve System (FRS)'), ('3', 'Federal Deposit Insurance Corporation (FDIC)'), ('5', 'National Credit Union Administration (NCUA)'), ('7', 'Department of Housing and Urban Development (HUD)'), ('9', 'Consumer Financial Protection Bureau (CFPB)')], help_text='A code representing the federal agency to which the HMDA-reporting institution submits its HMDA data.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_ethnicity',
            field=models.CharField(choices=[('1', 'Hispanic or Latino'), ('2', 'Not Hispanic or Latino'), ('3', 'Information not provided by applicant in mail, Internet, or telephone application'), ('4', 'Not applicable'), ('5', 'No co-applicant')], help_text='A code representing the ethnicity of the primary applicant.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_income_000s',
            field=models.CharField(help_text='The gross annual income that the lender relied on when evaluating the creditworthiness of the applicant, rounded to the nearest thousand.', max_length=8),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_1',
            field=models.CharField(choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the first listed race for the primary applicant. The applicant can list up to five races.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_2',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the second listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_3',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the third listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_4',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the fourth listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='applicant_race_5',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the fifth listed race for the primary applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_ethnicity',
            field=models.CharField(choices=[('1', 'Hispanic or Latino'), ('2', 'Not Hispanic or Latino'), ('3', 'Information not provided by applicant in mail, Internet, or telephone application'), ('4', 'Not applicable'), ('5', 'No co-applicant')], help_text='A code representing the ethnicity of the co-applicant.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_1',
            field=models.CharField(choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the first listed race for the co-applicant. The co-applicant can list up to five races.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_2',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the second listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_3',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the third listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_4',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the fourth listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='co_applicant_race_5',
            field=models.CharField(blank=True, choices=[('1', 'American Indian or Alaska Native'), ('2', 'Asian'), ('3', 'Black or African American'), ('4', 'Native Hawaiian or Other Pacific Islander '), ('5', 'White'), ('6', 'Information not provided by applicant in mail, Internet, or telephone application'), ('7', 'Not applicable'), ('8', 'No co-applicant')], help_text='A code representing the fifth listed race for the co-applicant.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='denial_reason_1',
            field=models.CharField(blank=True, choices=[('1', 'Debt-to-income ratio'), ('2', 'Employment history'), ('3', 'Credit history'), ('4', 'Collateral'), ('5', 'Insufficient cash (downpayment, closing costs)'), ('6', 'Unverifiable information'), ('7', 'Credit application incomplete'), ('8', 'Mortgage insurance denied'), ('9', 'Other')], help_text='A code representing the first reason for denial of the application. Lenders may report up to three denial reasons, but such reporting is optional.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='denial_reason_2',
            field=models.CharField(blank=True, choices=[('1', 'Debt-to-income ratio'), ('2', 'Employment history'), ('3', 'Credit history'), ('4', 'Collateral'), ('5', 'Insufficient cash (downpayment, closing costs)'), ('6', 'Unverifiable information'), ('7', 'Credit application incomplete'), ('8', 'Mortgage insurance denied'), ('9', 'Other')], help_text='A code representing the second reason for denial of the application.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='denial_reason_3',
            field=models.CharField(blank=True, choices=[('1', 'Debt-to-income ratio'), ('2', 'Employment history'), ('3', 'Credit history'), ('4', 'Collateral'), ('5', 'Insufficient cash (downpayment, closing costs)'), ('6', 'Unverifiable information'), ('7', 'Credit application incomplete'), ('8', 'Mortgage insurance denied'), ('9', 'Other')], help_text='A code representing the third reason for denial of the application.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='edit_status',
            field=models.CharField(blank=True, choices=[('', 'No edit failures'), ('5', 'Validity edit failure only'), ('6', 'Quality edit failure only'), ('7', 'Validity and quality edit failures')], help_text='A code representing the edit failure status of the application.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='hoepa_status',
            field=models.CharField(choices=[('1', 'HOEPA loan'), ('2', 'Not a HOEPA loan')], help_text='A code representing whether a loan is subject to the Home Ownership and Equity Protection Act of 1994 (HOEPA).', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='hmda_record_id',
            field=models.CharField(max_length=23, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='lien_status',
            field=models.CharField(choices=[('1', 'Secured by a first lien'), ('2', 'Secured by a subordinate lien'), ('3', 'Not secured by a lien'), ('4', 'Not applicable (purchased loans)')], help_text='A code representing the lien status. Most mortgages are secured by a lien against the property. In the event of a forced liquidation, first lien holders will generally get paid before subordinate lien holders.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='preapproval',
            field=models.CharField(choices=[('1', 'Preapproval was requested'), ('2', 'Preapproval was not requested'), ('3', 'Not applicable')], help_text='A code representing the pre-approval status of the application.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='property_type',
            field=models.CharField(choices=[('1', 'One to four-family (other than manufactured housing)'), ('2', 'Manufactured housing'), ('3', 'Multifamily')], help_text='A code representing the type of the property.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='purchaser_type',
            field=models.CharField(choices=[('0', 'Loan was not originated or was not sold in calendar year covered by register'), ('1', 'Fannie Mae (FNMA)'), ('2', 'Ginnie Mae (GNMA)'), ('3', 'Freddie Mac (FHLMC)'), ('4', 'Farmer Mac (FAMC)'), ('5', 'Private securitization'), ('6', 'Commercial bank, savings bank or savings association'), ('7', 'Life insurance company, credit union, mortgage bank, or finance company'), ('8', 'Affiliate institution'), ('9', 'Other type of purchaser')], help_text='A code representing the type of institution purchasing the loan.', max_length=1),
        ),
        migrations.AlterField(
            model_name='hmdarecord',
            name='sequence_number',
            field=models.CharField(help_text='A one-up number scheme for each respondent to make each loan unique.', max_length=8),
        ),
    ]
