# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0010_auto_20181209_2320'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='hmdarecord',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hmdarecord',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='hmdarecord',
            name='institution',
        ),
        migrations.AlterUniqueTogether(
            name='lendingstats',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='lendingstats',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lendingstats',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='lendingstats',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='HMDARecord',
        ),
        migrations.DeleteModel(
            name='LendingStats',
        ),
    ]
