# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmda', '0011_auto_20181218_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='LARYear',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
