# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 20:43
from __future__ import unicode_literals
from typing import List

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('weight', models.SmallIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('weight', models.SmallIntegerField()),
                ('layer_type', models.CharField(choices=[('v4', 'Old Style (v4)'), ('short_name', 'Short Name'), ('api_style', 'Api Style (Modern)')], max_length=16)),
                ('style_name', models.CharField(max_length=64)),
                ('active_years', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Category')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
    ]
