# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 04:57
from __future__ import unicode_literals
from typing import List

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('mapping', '0001_initial'), ('mapping', '0002_auto_20180322_2222'), ('mapping', '0003_auto_20181229_0439')]

    initial = True

    dependencies: List[str] = [
    ]

    operations: list = [
    ]
