# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='interaction',
            field=models.CharField(choices=[('base', 'Base'), ('metrics', 'Metrics')], default='metrics', max_length=16),
        ),
        migrations.AlterField(
            model_name='layer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Category'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='short_name',
            field=models.SlugField(max_length=32),
        ),
    ]
