#!/bin/bash

if [ ! -x "$(command -v virtualenv)" ]; then
  pip install virtualenv
fi

if [ ! -d .venv ]; then
  virtualenv .venv
fi

export VIRTUAL_ENV="/app/.venv"
export PATH="$VIRTUAL_ENV/bin:$PATH"
unset PYTHON_HOME

exec "$@"
