# Generated by Django 2.1.4 on 2019-01-20 03:52

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_squashed_0018_auto_20181229_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroDivision',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('interior_lat', models.FloatField()),
                ('interior_lon', models.FloatField()),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('geoid', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\d{5}')])),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.CoreBasedStatisticalArea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='county',
            name='metdiv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.MetroDivision'),
        ),
    ]
