# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20180214_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='cbsa',
            field=models.CharField(help_text='Core Based Statistical Area', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='csa',
            field=models.CharField(help_text='Combined Statistical Area', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='geo_type',
            field=models.PositiveIntegerField(choices=[(1, 'State'), (2, 'County'), (3, 'Census Tract'), (4, 'Metropolitan'), (5, 'Micropolitan'), (6, 'Metropolitan Division')], db_index=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='metdiv',
            field=models.CharField(help_text='Metro Division', max_length=5, null=True),
        ),
    ]
