# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20180218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='cbsa',
            field=models.CharField(blank=True, help_text='Core Based Statistical Area', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='county',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='csa',
            field=models.CharField(blank=True, help_text='Combined Statistical Area', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='metdiv',
            field=models.CharField(blank=True, help_text='Metro Division', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='geo',
            name='tract',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
