# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20180309_0358'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX geo_city_search",
            """ CREATE INDEX geo_city_search
                ON geo_geo(year, name)
                WHERE geo_type = 3
            """,
        ),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gin"),
        migrations.RunSQL(
            """ CREATE INDEX geo_city_search
                ON geo_geo
                USING gin(year, name gin_trgm_ops)
                WHERE geo_type = 3
            """,
            """ DROP INDEX geo_city_search """,
        ),
    ]
