# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20180318_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractProperty',
            fields=[
                ('relation_field', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='TractFeature',
        ),
    ]
