# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_auto_20180318_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractproperty',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tractproperty',
            name='name',
        ),
    ]
