# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_auto_20180319_0331'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='geo',
            index_together=set([('geo_type', 'centlat', 'centlon', 'year'), ('geo_type', 'maxlat', 'maxlon', 'year'), ('geo_type', 'state', 'county', 'year'), ('geo_type', 'cbsa', 'year'), ('geo_type', 'minlat', 'minlon', 'year'), ('state', 'year'), ('geo_type', 'maxlat', 'minlon', 'year'), ('geo_type', 'minlat', 'maxlon', 'year')]),
        ),
    ]
