# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_auto_20180403_0127'),
    ]

    operations = [
        migrations.RunSQL(
            """ CREATE INDEX geo_county_search
                ON geo_geo
                USING gin(year, state, name gin_trgm_ops)
                WHERE geo_type = 2
            """,
            """ DROP INDEX geo_county_search """,
        ),
    ]
