# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 03:25
from __future__ import unicode_literals

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20160222_2155'),
    ]

    operations = [
        TrigramExtension(),
    ]
